spring.application.name=DiscoveryService
server.port=8761

spring.cloud.discovery.enabled=true
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.server.enable-self-preservation=false
