
##### statical routing
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ecommerce-app-realm

      
eureka:
  instance:
    prefer-ip-address: true
  client :
    service-url:
      defaultZone : http://ecommerce-discovery-service:8761/eureka/




