
##### statical routing
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ecommerce-app-realm
  cloud :
      gateway:
        routes :
          - id : OrderService
            uri: lb://OrderService
            predicates:
              - Path=/api/orders/**
          - id : ProductService
            uri : lb://ProductService
            predicates:
              - Path=/api/products/**
          - id : ClientService
            uri: lb://ClientService
            predicates:
               - Path=/api/clients/**
      
eureka:
  instance:
    prefer-ip-address: true
  client :
    service-url:
      defaultZone : http://ecommerce-discovery-service:8761/eureka/




