# mongodb configuration
spring.data.mongodb.host=host.docker.internal
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecommerce
# redis configuration
spring.cache.redis.time-to-live=60000
spring.data.redis.port=6379
spring.data.redis.host=host.docker.internal
#  eureka service configuration
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/
eureka.instance.prefer-ip-address=true

# config client configuration
spring.cloud.config.enabled=false
