spring.data.mongodb.uri=mongodb://${USER_SERVICE_DB_HOST}:27017/${USER_SERVICE_DB_NAME}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.base-path=/actuator

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false